---

- name: Check existing cloud images
  ansible.builtin.stat:
    path: "/var/lib/libvirt/cloud-images/{{ item.url | urlsplit('path') | basename }}"
    checksum_algorithm: sha256
    get_checksum: true
  register: checksums

- name: Download cloud images
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    checksum: "sha256:{{ item.checksum }}"
    dest: "/var/lib/libvirt/cloud-images/{{ item.url | urlsplit('path') | basename }}"
    owner: root
    group: kvm
    mode: "0644"
  loop: cloud_images
